### ISSUE TITLE
Add a Verification tool

### ISSUE THREAD

**Issue by Loreinator** [Loreinator/Shuffle-Move#1]
A new board tool is needed to allow easy verification that you've entered the grid correctly. 

Needed features:
- A composite image of what the board should look like in-game (no borders or cursors)
- The number of species (both frozen and unfrozen)
- Synchronized with the main board at all time
- Position and size on the screen should be handled similarly to the Move Chooser dialog

Basic idea for layout is a simple window of one main image at the top, with a list of the species in the team and how many there are of each. Details on the number and their state should be something like: if there were 5 Gengar on the board and 2 were frozen, it should have the Icon like shown in the paint pallet, but where the keybind would be there would instead be **5 [2]** to denote 5 total, 2 frozen.

If anyone has any ideas on how to improve this concept for the verification tool, please let me know. I'll be working on it somtime.

**Comment by davd201** [comment]
Sound fine, I don't see what to add.

**Comment by Loreinator** [comment]
Idea from the survey results: Make a toggle to allow it to switch between the current board and the result board for the currently selected result.
