### ISSUE TITLE
French is not available from the menu

### ISSUE THREAD

**Issue by kpwbo** [Loreinator/Shuffle-Move#114]
Hello. :)

French is not available from the menu in version 0.3.47. I suspect this is because config/preferences.txt is not updated to include French as available locales (right now it's "STRING AVAILABLE_LOCALES en de fi zh"). Manually adding "fr" to the list does solve the problem.

**Comment by Loreinator** [comment]
Yes, it actually is - in the default stuff anyway. Just add in "fr" in that list in your preferences.txt file and it will appear when the program is next started.
