### ISSUE TITLE
Incorrect Glalie HP (Lvl 108)

### ISSUE THREAD

**Issue by megadrifter-pt** [Loreinator/Shuffle-Move#117]
Glalie has more than 7300 HP. Don't know how much exactly, but Shuffle Move stops at 5645 HP.

I'm playing on the latest Mobile version (on 03/29/16).

**Comment by Loreinator** [comment]
Confirmed, it actually is supposed to be 7350hp. I'll do an update to the mobile stages data with the next release.

**Comment by Loreinator** [comment]
Fixed in next release
