### ISSUE TITLE
Allow customization of the visual names in all GUI elements for species

### ISSUE THREAD

**Issue by Loreinator** [Loreinator/Shuffle-Move#12]
Localization should be done for all species. It should be very simple to do if done correctly.

The ideal place to store the config would be the species class itself, and the keys for the i18n should be the dex number (unique values that are not changed, no matter what, and are guaranteed to be correct). The name of the species will still be the key for configuration storage and board saving, though, to maintain semi-readable board files (for now).

**Comment by Loreinator** [comment]
If anyone knows about some source for a table of all species with their international names in each of the translated languages that would be awesome. Current translation languages are: German, Finnish, English, and Chinese. Obviously the English translations are the default, but we'll need to identify the correct translations for all 700+ species (so we don't have to keep going back to it).

**Comment by kpwbo** [comment]
This should cover most of the names :
[German names](http://bulbapedia.bulbagarden.net/wiki/List_of_German_Pok%C3%A9mon_names)
[Chinese names](http://bulbapedia.bulbagarden.net/wiki/List_of_Chinese_Pok%C3%A9mon_names)
You can click on "view source" at the top of the page for perhaps easier parsing.
I do believe that there are no Finnish Pokémon names, as the games distributed in Finland are in English. The [official Finnish Pokémon website](http://www.pokemon.com/fi/pokedex/) uses the English Pokémon names.
You may have to ask the translators for some special names such as for Rotom's formes.

**Comment by Loreinator** [comment]
Thanks for those links, I've now compiled nearly all the required keys (99%)

**Comment by Loreinator** [comment]
Currently added in and functional in the development branch. This does not include stage names, though since that uses an entirely different system for naming.
