### ISSUE TITLE
Ampharos mega no longer gets points for erasing air

### ISSUE THREAD

**Issue by Loreinator** [Loreinator/Shuffle-Move#137]
Recently it has been discovered that Mega Ampharos's ability does not add points for post-active erased tiles. The "air" no longer gives any bonus points for being included in the animation, although the animation looks like it is erasing it.

**Comment by avengah** [comment]
Now that I think about it, it's probably all Megas that have the ability to erase empty tiles, such as Lucario, Venusaur, Blastoise, Garchomp etc. although this would be a nightmare to test for each one.

**Comment by Manitary** [comment]
I experienced it today with M-Lucario, luckily I remembered about this issue and didn't go further with SM so I have the board state available: ![m-luke](https://cloud.githubusercontent.com/assets/11020501/15273374/ec06ad8e-1a97-11e6-8c2d-d571040cbb2a.png). Lucario is lvl max (90atk) and Gallade lvl 8 (86atk).

The second hit of the combo dealt 702 damage, while the base damage of a 3-match M-Lucario is 720 (20*18*2 I guess?). But SM did the computation right: indeed, the damage of the selected move is 86*2 + 702 = 874.

**Comment by Loreinator** [comment]
So far it looks like it may be that all mega effects no longer give bonus points for "active OR empty" (meaning, score added but not erased, or fully erased and no tiles have fallen into it yet). It may be that some of them still 'hold' those un-counted tiles as active and prevent falling blocks from going through them for a short period, but until we see examples of them in the future or until I have time to test every mega again I will leave them in the simplest implementation: To simply not add those tiles to the 'to erase' list, so they are ignored entirely for both score and 'holding'.

**Comment by Loreinator** [comment]
I've made the change for the next version, the affected megas will now filter their next 'plan' by excluding all active or air blocks. Also, as discovered previously some of them also exclude falling blocks.

No Active or Air:
Latios, Latias, Manectric, Scizor, Sableye, Altaria, Audino, Blastoise, Ampharos, 

No Active or Air or Falling:
Kangaskhan, Lopunny, Abomasnow, Venusaur, Lucario, Gardevoir

The other mega effects are unaffected by this change.
