### ISSUE TITLE
Psyduck is missing from the roster

### ISSUE THREAD

**Issue by wrulfy** [Loreinator/Shuffle-Move#140]
Psyduck doesn't appear on the roster, it skips from zygarde to golduck
It doesn't appear on the default board of the stage 352.

After manually adding Psyduck with the Edit species option, it started appearing in the default board of said stage
[bugReport_20160520_200957_CEST.zip](https://github.com/Loreinator/Shuffle-Move/files/275200/bugReport_20160520_200957_CEST.zip)

**Comment by Loreinator** [comment]
Hrm... I'll have to check it when I get home. According to the source code it should be there and usable.

**Comment by Manitary** [comment]
I just redownloaded the client to be sure and it seems to work just fine.

**Comment by Loreinator** [comment]
Upon inspection of the bug report zip I have identified the cause of this problem. Did you by any chance add Zygarde manually before it was released? Psyduck has an internal number of 504, which is currently held by Zygarde in your species.txt config.

This is functioning as intended - User-set species should override the species included in the program. This is part of why the Species Editor is only recommended for advanced users - you need to ensure that there are no inadvertent collisions of the species names or numbers. 

Recommended fix: Delete your species.txt file and then load and save the program. This will wipe all your species overrides and ensure you get clean upgrades from now on.
