### ISSUE TITLE
Non-support Pokemon not counting towards by rank by disruptions

### ISSUE THREAD

**Issue by wrulfy** [Loreinator/Shuffle-Move#147]
I tried today on magmortar stage, while having tyranitar in my team, that changing the grading to rank by disruptions, Shufflemove doesn't consider non-support pokemon as disruptions, both when there's eject matches avaiable (and not other rocks/metal blocks) and when there was a 5 match that would clear several magmortar.

**Comment by Loreinator** [comment]
I think I'll have to add on a new metric - non-support erased.
