### ISSUE TITLE
Info on Duplicated Matches Trick

### ISSUE THREAD

**Issue by zero2exe** [Loreinator/Shuffle-Move#15]
Alright so here's what I know about duplicated matches:
1.- In order to trigger it you need a match to resembles a certain shape which is either an "L", "reversed L" or an inverted "T" as depicted in this example http://prntscr.com/86lnu5
You will always need at least 5 icons to perform this and 7 is the cap. This is because the Vertical part of the match should never go below the horizontal one, otherwise the trick won't work and you'll just perform a normal combo.
In this example you can see the max number of icons you can use while still performing the trick http://prntscr.com/86lqmd
Other shapes like these http://prntscr.com/86lv9j will NEVER proc the trick since the vertical part of the match goes below the horizontal one.
2.- As far as activation orders go, the horizontal line that serves as the match's base will always proc first. The vertical section will always proc in second place.
3.- The horizontal line will activate "twice" and the game doesn't seem to account it as a combo since both blows deal the exact same damage. The vertical portion of the match however works as intended and gets the usual damage boost for performing a combo.
4.- Another neat property of this trick is that if you start your turn with it and it procs an ability like crowd control that effect will also be duplicated for that portion of the attack. This property also applies to coins in the meowth stage so an inverted "T" match will award you 300 coins instead of 200.
5.- You can also begin with another different match and turn this one into part of the combo which will be duplicated with the corresponding combo boost. For example you could start the combo with Darkrai and then Genesect will follow clearing the horizontal section Twice while applying the 1st combo boost on both blows to finally initiate the vertical part which will be further boosted as if it was the third match in the combo. http://prntscr.com/86lrl3

**Comment by Loreinator** [comment]
A few questions we need to answer before this can be properly simulated: 

1. How much does it advance the chain when this occurs in the middle of a combo? 

2. How does this affect frozen blocks if they are
a) Part of the horizontal component only, 
b) Part of the vertical component only
c) At the intersection

3. What is the exact frame-based timing of the sequence from recognition to final erasure? The normal combo can activate every 24 frames and takes 82 frame to erase (4 more frames for wood, 1 more frame for frozen to thaw). Some mega abilities happen on 8 frame or 10 frame intervals, A block takes 16 frames to fall. [See here for the program I used to step through 240fps footage to identify the timings for everything else.](http://www.opensourcephysics.org/items/detail.cfm?ID=7365)

That's all I can think of for now, I might have more things that need clarification as we discuss this further.

**Comment by JustAnotherRandomLad** [comment]
1. The glitch never adds extra counts to the combo.

2. It doesn't. The blocks are unfrozen as normal, the extra damage still kicks in, etc. (But I can't say for sure in case (c), considering how rare that is in the game - in fact, it's physically impossible in the absence of disappearing metal blocks and complexity alterations. I'd assume it's the same as a) and b), though.)

3. Same as a normal combo; the extra "hit" doesn't affect icon erasing rates.

**Comment by Loreinator** [comment]
[Copy paste from reddit.](https://www.reddit.com/r/ShuffleMove/comments/3heevo/release_shuffle_move_v0318_is_released/cuaqa9s)

Oh, I can tell you all that right now:

* Mega progression is unaffected by the glitch (so a 3x3 inverted T-match will boost it by 6).

* Timing is unaffected in terms of falling icons; the match is erased as if the glitch didn't exist, and the extra damage is just tacked on immediately after the first hit.

* Frozen blocks behave normally, apart from the damage boost.

* Blocks are released at the same rate as if the glitch did not occur.

* Combos are counted as if the glitch did not occur. The first "counting" of the vertical line is done with the same combo modifier as the horizontal line, and the second is done with one more point on the combo counter.

* Effects are triggered as normal (i.e., depending on the horizontal line length), but any damage modifiers applied to that line as a result (for example, Power of 4 or Crowd Control) are also applied to the first "counting" of the vertical line, regardless of what the effect is - so, in the case of Power of 4+, the first counting of the vertical line would be tripled in damage despite only being 3 icons long. The second behaves normally. ~~(I'll edit this post when I figure out how icons are counted for Crowd Control.)~~ (EDIT: Effects unrelated to damage, like Mega Boost and Block Smash, are *not* activated twice.)

* Disruption triggers follow the combo counter, which, like I said earlier, isn't affected by the glitch. So a single L-shaped match alone won't set off coin spawns on Weekend Meowth. (However, activating the glitch on a coin match *will* effectively double the value of the vertical line.)

Cheers! :)

EDIT 2: IIRC, activating Vitality Drain in this fashion results in net damage equal to 20% of the opponent's HP on activation, plus the normal score for the vertical line. I'll test it again when I get the chance, just to be sure.

EDIT 3: 4x3 inverted-T match of LvMAX Genesect (100 AP) on Darkrai with 4 other Genesect on the board dealt 650 for the horizontal, 550 for the first vertical, and 220 for the second vertical. Accounting for line lengths, this indicates that each CC-boosted line counted 7 icons for the boost; subtracting the 4 from elsewhere leaves 3 within the cross that were counted in each case. If the vertical match's CC boost was calculated separately from that of the horizontal line, it would have included either the entire horizontal line (4), just the intersection point (1), or no parts of the cross-match (0), depending on when it was calculated. One could argue that the second possibility is invalid, but this is irrelevant; none of these match the count of 3 that was observed, anyway.

Conclusion (and TL;DR): **Both lines receive the Crowd Control boost as calculated from the horizontal line.**

**Comment by Loreinator** [comment]
1) Can this effect, in rare instances, be triggered with more than 1 vertical line, [such as in these cases](http://imgur.com/a/7TQze), or does this effect only include one vertical line, and if so is it the leftmost vertical, or the leftmost largest vertical?

2) Can this effect trigger in [this case](http://imgur.com/d25fZ59) with a 4x horizontal and 4x vertical? (this assumes the 4x vertical is from an extremely lucky fall or cascade)

Once all the fine points have been exhausted, I should have enough data to properly implement the effect in the perfect point in the simulation.

**Comment by JustAnotherRandomLad** [comment]
No idea on either one - haven't seen them before - but I'd assume the answer to (2) is yes.

I'll watch for matches like those, but any idea how I could set one up?

**Comment by Loreinator** [comment]
In some stages you get really lucky with the skyfall, so you might be able to see it happen on things like the 3-mon stages. It would probably take recording the footage of a massive chain to ever catch it though.

**Comment by JustAnotherRandomLad** [comment]
Still haven't seen them yet, but I did see an L-shaped M-Blaziken match fall into place, and it activated the glitch; only the horizontal line was removed, but the vertical line was also scored once. Can't say for sure whether the effect activated twice, but it looked like it didn't.

**Comment by Loreinator** [comment]
For mega evolved species, they immediately release all intersecting combos before their activation fully takes place. [See here for where I've included this behavior.](https://github.com/Loreinator/Shuffle-Move/blob/master/src/shuffle/fwk/data/simulation/effects/ActivateComboEffect.java#L65)

**Comment by JustAnotherRandomLad** [comment]
**Answer to (2) in previous list is confirmed to be "yes".** (Source: Weekend Meowth, 4x4 inverted-T of coins.)

**Comment by JustAnotherRandomLad** [comment]
FWIW, this trick is *not* present in the mobile version of the game. If you're going to make it compatible with that version, you should allow users to choose their version and have damage calculations performed accordingly.

**Comment by JustAnotherRandomLad** [comment]
Another Weekend Meowth confirmation: if the vertical line is longer than the horizontal one, the glitch does *not* activate.

**Comment by Loreinator** [comment]
Ok, so far it seems like the following is true:

- It requires the match priority of the horizontal to be greater than the vertical.
- The vertical must have its lowest block equal to one of the horizontal match's coordinates
- The score boost is such that it activates effects twice, effectively. For all effects (crowd control, power of 4, etc.) even if the effect couldn't have activated with the vertical normally. 

Correct me if any of these are wrong, I don't want to implement the simulation of this glitch incorrectly or the results could be useless or misleading.

**Comment by JustAnotherRandomLad** [comment]
The effect doubling is only in terms of damage - you can't break 6 barriers at once with Cresselia, for example. But other than that, yes.

**Comment by Loreinator** [comment]
Just revisiting this - thinking of pushing it in *soon*:

1) Whenever a horizontal match is activated, look for any pending matches that are:
- vertical
- shorter than the horizontal match
- inactive
- have their lowest point as part of the horizontal match.

2) if you find any, then for EACH match, perform the following:
- Add on score as if the vertical was 'completed' normally right now
- Add on any bonus score if the match could have it, as if it activated itself. This will include Crowd Control, Power
- Do nothing else, no other effects or unfreezing nor activation of the vertical potential match.

If that's correct, then I'll be good to go and implement some code to handle it in the next release - I've held off until now in hopes that Nintendo would fix their obvious bug. They haven't fixed it, so I am guessing it is here to stay for the life of the game.

**Comment by JustAnotherRandomLad** [comment]
Vertical 3-matches affected by this get any Power bonus applied to the horizontal match. As long as you include this, then yes, it sounds right.



Sent from my Samsung device


-------- Original message --------

**Comment by Loreinator** [comment]
Missed a couple cases, continuing to work on it.

**Comment by Loreinator** [comment]
OK, got the last case in - that Blaziken L match case was missing.

It has been implemented with this logic:

- All L or inverse T matches, where each vertical is no longer than the horizontal.
- 3DS Mode only
- Either effect is NOT mega, OR the chain is more than 0

Then, if observed:
Bonus value is multiplied by (1 + # of glitch combos)
Main score adds on the glitch combo's normal score in addition to the normal score of the primary combo.

Try it out here: https://drive.google.com/uc?id=0Bwi_f200YyRqV25FWmJmOFY3a3c&export=download

MD5sum is EB5D95D38219F8068A3EB112FBDCB579

If there are no bugs reported against this issue before the next patch's update it will go in for the main release.
