### ISSUE TITLE
Mega State incorrectly counts thawed icons

### ISSUE THREAD

**Issue by Manitary** [Loreinator/Shuffle-Move#168]
The Mega State should count only erased icons (except with crossing matches), so if an icon is blocked by a barrier and thawed by matching it, it shouldn't count for the progress.

![bug_mega_thawing](https://cloud.githubusercontent.com/assets/11020501/16356816/7a79df06-3ae5-11e6-8242-a7e233433629.png)

For some reason the website is not allowing me to upload the bug report file, so if you need it you can find it [here](https://drive.google.com/open?id=0BxmJc9E6cHiIZ0U4NTZTSmFzaFU).

**Comment by avengah** [comment]
I can see a second mistake in that screenshot. Looking at the Move Chooser, the range is shown as 72-1072, but shouldn't it be 72-1000? Because if Vitality Drain activates, Venusaur's power isn't taken into account at all; it's a fixed 10% of remaining HP, which is exactly 1,000 in this case.

**Comment by Manitary** [comment]
I always thought the calculation was "drain damage + match damage", but you're right!
