### ISSUE TITLE
Combos aren't counted correctly in v0.3.18

### ISSUE THREAD

**Issue by JustAnotherRandomLad** [Loreinator/Shuffle-Move#17]
When a move is made that results in either matches at both ends or a cross-match, SM doesn't seem to apply the combo damage boost to the second line anymore.

Bug report zip: http://ge.tt/4v8ydbM2/v/0

**Comment by Loreinator** [comment]
This is already fixed in v0.3.19 on the development branch.

[See here for the fix](https://github.com/Loreinator/Shuffle-Move/commit/b08fda2ef06f55b82b9b9126661236ad0264be7e)
