### ISSUE TITLE
Stabilize is not working properly 

### ISSUE THREAD

**Issue by Manitary** [Loreinator/Shuffle-Move#170]
* If it targets a barrier, it should act like Barrier Bash. Instead, the whole icon is erased, like Eject.
* Sometimes it erases only 1 disruption while there are 2 available. It should remove both, even if they are of different type (e.g. Barrier and Wood).

MWE: 
![stab](https://cloud.githubusercontent.com/assets/11020501/16361781/5a986520-3b9b-11e6-977e-05f07d6e656b.png)

[Link to the bugreport file](https://drive.google.com/open?id=0BxmJc9E6cHiIYTMtcjBLNzBEQ3c)

**Comment by Loreinator** [comment]
Should be fixed as of dev version 213 or later.

See here for all dev versions: 
https://drive.google.com/drive/folders/0Bwi_f200YyRqfm5fOWMtbkVrd0RhQUJyTDR6V29WZFFBd0o4cl95VjlqUTkyNDRicS1GOVE

**Comment by Loreinator** [comment]
Found a secondary cause for point 2 about sometimes erasing only one. Fixing now...

**Comment by Loreinator** [comment]
Should be completely fixed as of build 215
