### ISSUE TITLE
Include Moves +5's effect to the Moves counter

### ISSUE THREAD

**Issue by kpwbo** [Loreinator/Shuffle-Move#19]
It would be nice to allow the "Moves" counter to be set to 1-5 more than the stage's base number of moves, to better simulate the effect of using a "Moves +5" item, which can be useful for abilities that depend on the number of moves (Last-Ditch Effort for example).

For example, if a stage's base number of moves is 15, the "Moves" counter would be initially set at 15, but it would be possible for the user to set it to 16, 17, 18, 19 or 20 (as well as 0 to 14).

**Comment by Loreinator** [comment]
[Fixed and closed.](https://github.com/Loreinator/Shuffle-Move/commit/94c22f4efa8937bbf24e24686c403597074b6d42) This was surprisingly fast and risk free to implement, given your use case you described - its simply a 1-line alteration in the paint pallet GUI code itself. Probably one of the fastest issues yet!
