### ISSUE TITLE
how to change skill of raikou?

### ISSUE THREAD

**Issue by iampkuhz** [Loreinator/Shuffle-Move#214]
hi, I have change the skill of my raikou to barrier bash+.
however, I found no where in the simulator that can change the ability.

Could anyone give me some advise ?

thanks~

**Comment by Loreinator** [comment]
Roster Editor -> Select Raikou -> then select the effect chooser at the bottom to select barrier bash+.

**Comment by iampkuhz** [comment]
thanks~
