### ISSUE TITLE
Replace HP with Score

### ISSUE THREAD

**Issue by kpwbo** [Loreinator/Shuffle-Move#22]
I think the HP counter should be replaced with a Score counter. The two are basically a measure of the same thing when playing a stage (`score = maxHP - remainingHP`). However, unlike the remaining HP which has to be manually calculated by the user, the score can directly be read from the game. It is therefore easier for the user to adjust the score/HP by adjusting the score than by adjusting the HP.

![](http://i.imgur.com/f58xRQN.png)
[Screenshot from https://www.youtube.com/watch?v=wTLUw560PRs]

**Comment by Loreinator** [comment]
Maybe not replaced, but perhaps just supplemented by the addition of a score counter beside it, and they both modify the same internal 'score' count while the hp just displays stage health minus score (but not negative).

**Comment by Loreinator** [comment]
Slightly tweaked idea: Have HP as a simple label that is updated to maintain its validity, with the field that is currently for HP to be for "Score".

**Comment by Loreinator** [comment]
Issue resolved in development branch.
