### ISSUE TITLE
Replace Metal with 5 types of Metal

### ISSUE THREAD

**Issue by kpwbo** [Loreinator/Shuffle-Move#23]
The basic idea is to replace the current Metal block with 5 types of Metal Blocks, so that the simulation can know when a Metal Block with disappear.

The Metal block icon would be replaced with 5 different Metal block icons, each one of them having a different number from 1 to 5 on it. The 5 icons act as independent "species". When the "Metal" checkbox is checked, all 5 would be able to be picked and placed by the user.

When the simulation occurs, Metal blocks "5" would be replaced with Metal blocks "4", Metal blocks "4" with Metal blocks "3", etc., and Metal blocks "1" would disappear from the board. I'm not sure exactly of the timing of the disappearance of Metal blocks and when the disappearance happens relatively to the activation of certain abilities (such as Mega Aerodactyl's ability), so this probably needs more research.

This should make the simulation more accurate.

**Comment by Loreinator** [comment]
Going well, just testing it now...

**Comment by Loreinator** [comment]
Click them to make them progress, or do a 'move' result to advance them
as well. They become air as soon as they expire, which occurs after the
moves are checked for valid moves (can't move inside a disappearing
metal block) but before those moves are simulated.

**Comment by Loreinator** [comment]
[Test version ready. Please back up your config folder before you launch and/or save with this version, or you might have issues when upgrading to it later on. I personally never save when using a development version due to the hassle of backing up configurations.](https://drive.google.com/open?id=0Bwi_f200YyRqNjZ4QVgwR182VU0)

**Comment by Loreinator** [comment]
I've done some testing with it and it appears to be bug-free. Closing issue since this is now resolved in the Development branch.
