### ISSUE TITLE
Different effect implementation on mobile and 3DS

### ISSUE THREAD

**Issue by Manitary** [Loreinator/Shuffle-Move#243]
I noticed that [effect.txt](https://github.com/Loreinator/Shuffle-Move/blob/master/resources/config/defaults/effects.txt) and [effect_mobile.txt](https://github.com/Loreinator/Shuffle-Move/blob/master/resources/config/defaults/effects_mobile.txt) only differ by the following:

`STRING BURN 5 55 80 100 5 10 15 20 ODDS`
`STRING BURN 5 55 80 150 5 10 15 20 ODDS`

`STRING SPOOKIFY 5 45 80 100 10 15 20 30 ODDS`
`STRING SPOOKIFY 5 45 80 150 10 15 20 30 ODDS`

`STRING FREEZE 5 35 70 100 10 12 15 20 ODDS`
`STRING FREEZE 5 35 70 120 10 12 15 20 ODDS`

`STRING SLEEP_CHARM 5 30 80 100 10 15 18 25 ODDS`
`STRING SLEEP_CHARM 5 30 80 120 10 15 18 25 ODDS`

**Comment by Loreinator** [comment]
Do they still handle the effects differently for the score multiplier?

The fourth number is a % of normal damage modifier (the use of which depends on the effect). From this it looks like the mobile version is configured to consider them as boosting store, while the 3ds configuration (effect.txt) does not.

Should it be changed?

**Comment by Manitary** [comment]
It seems to work correctly both ways, with Mobile mode enabled or not.

Tested with Charmander/Charizard (which has Burn), Burn already active/Burn inactive, Sleep Charm active/inactive.

**Comment by Loreinator** [comment]
The ongoing effect multiplier is defined by the Board.Status enumerator, I think the multiplier in the effect.txt configs only would affect the initial match itself.
