### ISSUE TITLE
Add Power of 4 for MMX's Mewtwo

### ISSUE THREAD

**Issue by Loreinator** [Loreinator/Shuffle-Move#247]
post replyShuffle Move v0.3.89

from G996 via /r/ShuffleMove sent 6 minutes ago

The Mewtwo which mega evolves to MMX can't be Skill swapped for Po4. Can you fix this in the next update?

https://www.reddit.com/r/ShuffleMove/comments/5ot610/shuffle_move_v0389/dcmx2gi/?context=3

**Comment by Manitary** [comment]
Ah I missed the fact that Mewtwo has two entries in the species file, the second one is missing the alternate ability.
