### ISSUE TITLE
GUI helpfullness improvement - ToolTips

### ISSUE THREAD

**Issue by Loreinator** [Loreinator/Shuffle-Move#26]
[See here for how to implement in java](https://docs.oracle.com/javase/tutorial/uiswing/components/tooltip.html)

This needs to be added to all GUI buttons, labels, and fields in the program (not images, icons, or menu items). 

The tooltips need to use i18n keys to obtain their text, allowing full localization of their helpfulness.

There are a LOT of gui components to put this on, so it will be a large amount of code additions as well as a lot of translation work for our translators.

**Comment by kpwbo** [comment]
Hi. :)

I think I can work on this. I have forked Shuffle Move and gave it a try to see how it works.

Can you check [this commit](https://github.com/kpwbo/Shuffle-Move/commit/bc69ce8591b63cd602d064e75327bccefe92d81e) and tell me if that is how it is supposed to be done ? Of course, I'll have to add the i18n keys for all the languages, which I forgot to do at first. For the non-English languages, do I keep the English text until the translations are available ?

Here's a screenshot of the added tooltip (the mouse is over the checkbox) 

![](http://i.imgur.com/1CvLDvo.png)

**Comment by Loreinator** [comment]
Yea, that's generally how it's done - new keys go in the non-locale i18n
properties file first though, so they can be the baseline for all other
languages (Java i18n inheritance). I'll give some more detail on the
process tomorrow evening in 17-18 hours (I'm actually in bed about to sleep
right now, typing this on my phone).

On Oct 7, 2015 12:26 AM, "Kpwbo" <notifications@github.com> wrote:
>
> Hi. :)
>
> I think I can work on this. I have forked Shuffle Move and gave it a try
to see how it works.
>
> Can you check this commit and tell me if that is how it is supposed to be
done ? Of course, I'll have to add the i18n keys for all the languages,
which I forgot to do at first. For the non-English languages, do I keep the
English text until the translations are available ?

**Comment by Loreinator** [comment]
Yup, that's the general process of how to use i18n in the Shuffle Move. 

Just a note though: The process I usually follow for introducing new i18n is:

1. Create keys in the base properties file for that class. For this, it would mean making your tooltip entry in EditRosterService.properties
2. Copy those keys over to the english properties files (_en and _en_CA)
3. If there are only a couple keys, then send them off in a simple comment to each of the translators - when they respond it goes in to the next release. We don't wait for responses because they are low priority (just cosmetic) and the translators have lives and stuff that may keep them busy for a while. **However** if there are a large volume of keys, then they should be compiled simply into a file on their own and shared with the translators for them to update them.
4. When the translations come back, the process is rather simple: Copy them into the native side of http://native2ascii.net/ and hit the arrow to convert the text. Then copy the result on the right side and paste it into notepad. Finally, copy the appropriate entries into each of the localization files.
5. When complete, commit the changes and sync to the github repository. The build should automatically be built and uploaded to Google Drive [here](https://drive.google.com/open?id=0Bwi_f200YyRqfm5fOWMtbkVrd0RhQUJyTDR6V29WZFFBd0o4cl95VjlqUTkyNDRicS1GOVE) (Note this is only for commits made to the master branch of Loreinator/Shuffle-Move).

One other note about the code side: Some of the more 'live' components might update the i18n on the fly, you should probably check that you're able to retrieve the tooltiptext from the GUI Component directly or there will need to be separate tracking to handle that. One good example is the Entry Mode Panel - swapping the language will make it change text, so if the language is swapped the tooltips should also be updated.
