### ISSUE TITLE
Correct Wood Shatter Logic

### ISSUE THREAD

**Issue by Loreinator** [Loreinator/Shuffle-Move#27]
Occasionally, when a match is falling beside a column of wood, the wood will NOT actually shatter the top block beside the combo. 

There needs to be more data on exactly what conditions this happens in so we can narrow down the exact algorithm for determination of this behavior.

**Comment by JustAnotherRandomLad** [comment]
You mean in the game?

I always figured that was just a result of the unfreezing delay, but does it really happen when nothing was frozen? If so, I'll keep my eyes peeled.

**Comment by Loreinator** [comment]
Yup, I just witnessed today that there was a vertical combo beside a wall of wood/rock for which only the bottom two actually were shattered. The top of the 3 on the right side of it was not shattered.

Since this inaccuracy is not accounted for in the simulation, anytime it happens the simulation could deviate significantly from what will REALLY happen.

**Comment by JustAnotherRandomLad** [comment]
[Does this help?](http://ge.tt/8mjP6kM2/v/0)

**Comment by JustAnotherRandomLad** [comment]
Can now 100% confirm that this is the same deal as with unfreezing blocks: wooden blocks take one frame longer to finish disappearing than regular icons.

(Also, the mobile version does the same thing.)

**Comment by Loreinator** [comment]
Yes, the delay was known already - actually wood is 3 frames, and ice is 1 frame.

Btw for some reason firefox has banned ge.tt from allowing it to download stuff. Can you reupload to google drive or another file sharing service?

**Comment by JustAnotherRandomLad** [comment]
Wait, really? Huh.

And sure thing - I'm not having any problems with it at my end, but I'll try putting the file somewhere else shortly.

**Comment by Loreinator** [comment]
Yea, whenever I try to download from ge.tt now firefox simply downloads it as a 0kb file (empty). It might have something to do with windows 10.

**Comment by JustAnotherRandomLad** [comment]
Ah, yeah, probably - I've been holding off on updating until all the kinks are worked out.

**Comment by Loreinator** [comment]
I think I'm going to go with https://www.dropbox.com/ since there are no adverts on the download page by default.

**Comment by JustAnotherRandomLad** [comment]
Sorry for the delay - [how's this?](https://drive.google.com/file/d/0B9AJEgC2diKdRGZ0WWZaZ3dTc3M/view?usp=sharing)

**Comment by Loreinator** [comment]
New information from [here](https://www.reddit.com/r/ShuffleMove/comments/3lf0xt/found_a_pair_of_bugs_with_barriers_and_rocks/)

I was doing Klink stage, using honedge as token for klink. found two things: The frozen tiles of a match won't clear rocks that are touching it. Not sure if is due to the own rock being frozen, but the thing was like this: rock: w honedge as klink: x

wf

xf

xf

x

when doing that match, the 2 honedge-kink are unbarriered, however, the rock remains barriered, not cleared.

also, if a normal match that is touching a rock under a barrier, and said match activates barrier bash, if barrier bash was going to unbarrier that rock, it woulnd't break.

on the same stage, I was trying to get rid of the last barrier with emboar, it was like this:

wf

e e e

instead of clearing the rock like in normal circunstances, emboar activates barrier bash, clearing the barrier, but letting the rock unbroken.

**Comment by JustAnotherRandomLad** [comment]
Oh, yeah, I thought you knew the first one already. I didn't know the second, though - that's interesting...


Sent from my Samsung device

-------- Original message --------

**Comment by Loreinator** [comment]
Yup, I classify it all as falling under "fix wood shatter logic" so that when a fix is put in it will cover all aspects of this bug - or most of them anyway.
