### ISSUE TITLE
Spooky Gengar

### ISSUE THREAD

**Issue by Pepperapril** [Loreinator/Shuffle-Move#280]
Spooky gengar is not working - the icon in shuffle move may be for shiny gengar based on appearance.

**Comment by Manitary** [comment]
I thought it was fixed with the last release...meanwhile, you can fix it manually as described [here](https://www.reddit.com/r/ShuffleMove/comments/64r7w4/big_issues_with_poison_pok%C3%A9mon/dg9b9g9/)
