### ISSUE TITLE
Piplup line is missing from roster

### ISSUE THREAD

**Issue by tristan1301** [Loreinator/Shuffle-Move#285]
I tried adding Piplup and Empoleon, and could find neither of them.

**Comment by Manitary** [comment]
Well, they are not in the game (yet)

**Comment by tristan1301** [comment]
Well, then why is Piplup appearing in the Popplio stage?

**Comment by Manitary** [comment]
GS choice...we don't know anything about it though. I suppose we could check the bp by looking at its match damage, and someone willing to waste hearts could try to match it repeatedly at the start of the game to check what is its ability.

The old info is 30BP Opportunist, but that's just a placeholder, I have no idea whether they updated it or not. If they did, I'll update it as soon as I get the info.

**Comment by tristan1301** [comment]
Eh, i've got 90 lives to kill. I'll try it out.

**Comment by Manitary** [comment]
That's a bit of a waste :[ I was thinking of leaving it to someone with a hacked 3DS

**Comment by Manitary** [comment]
Thanks to a hacked 3DS we know Piplup is 50BP Po5, I will add it next Tuesday with the new update
