### ISSUE TITLE
Cross attack+ damage isn't calculated correctly

### ISSUE THREAD

**Issue by ZeroRin** [Loreinator/Shuffle-Move#302]
skill level only affect the first match dealt by ca+, but shuffle move also applies it on the second match

for example, a 3+3 cross match should deal 90x12+90x1.1x4=1476 damage
but shuffle move calculates as 90x12+90x1.1x12=2268 damage
didn't check other X L T skills but i guess they may also be incorrect

**Comment by Loreinator** [comment]
I wasn't aware that skill levels weren't counted on the secondary match. I've put in a fix and it now calculates 1476 in the scenario you presented. You can find the fixed version in the development folder here:

https://drive.google.com/open?id=0Bwi_f200YyRqfm5fOWMtbkVrd0RhQUJyTDR6V29WZFFBd0o4cl95VjlqUTkyNDRicS1GOVE
