### ISSUE TITLE
"choose move" subwindow can't be recovered if it was ever offscreen

### ISSUE THREAD

**Issue by EvilProfesseur** [Loreinator/Shuffle-Move#309]
The problem may be related to multi-monitor use. The subwindow's position is retained within the app and if for some reason it went offscreen it can never be recovered. Might be also related to the problem of the main window stretching to several times its original width after restart (I wasn't able to reproduce it reliably, it just happens randomly). Right now if I select "choose move" nothing happens

temporary solution: set INTEGER CHOOSER X / Y to 0 / 0 in userfolder/shuffle-move/config/preferences.txt

**Comment by Loreinator** [comment]
Did you try removing the CHOOSER_X and CHOOSER_Y entries entirely? That should revert it to the default location.

**Comment by Loreinator** [comment]
I've added a new feature issue for fixing this in a more permanent way later on:

https://github.com/Loreinator/Shuffle-Move/issues/310
