### ISSUE TITLE
"F" key no longer works to freeze icons in Express Mode

### ISSUE THREAD

**Issue by JustAnotherRandomLad** [Loreinator/Shuffle-Move#31]
See title. Probably an easy fix.

**Comment by Loreinator** [comment]
Yup, null pointer... Debugging now.

**Comment by kpwbo** [comment]
I'll add that the "F" key works in Express Mode until the moment when the cursor goes above the board.

**Comment by Loreinator** [comment]
One line fix, 

About the F key in express mode, can you elaborate? I can't tell what you mean by that.

**Comment by Loreinator** [comment]
Fix for null pointer is [here](https://github.com/Loreinator/Shuffle-Move/commit/cf7bb10d7a069710a1be32df452308e3a0faadb6).

**Comment by Loreinator** [comment]
Closing for now, @kpwbo if that is still an issue after the rushed release of v0.3.21 please resubmit as a new issue with all possible information.

**Comment by Loreinator** [comment]
V0.3.21 is now out, please check if it adequately resolves this issue.

**Comment by JustAnotherRandomLad** [comment]
Works great for me now, thanks!

**Comment by Loreinator** [comment]
Awesome! I'm glad I could find the problem quick enough.
