### ISSUE TITLE
Add option to reset popup locations

### ISSUE THREAD

**Issue by Loreinator** [Loreinator/Shuffle-Move#310]
See title. All popups that retain their position should have their position reset by a single option in the help menu. It could be called something like "Reset all popup locations".

The actual effect of it could be something like: Relocate all popups to "null", and save their new positions. This should center everything.

**Comment by EvilProfesseur** [comment]
wouldn't it be better to check if the saved position is offscreen and automatically reset it if it is? Don't know if you can check for that, I never worked with windows api.

**Comment by Loreinator** [comment]
Just added in the fix, with an automatic move back to the 'default location' of the screen if the window is moved, or tries to move, to an offscreen position.

You can disable this safety by adding this line to your preferences.txt file:

BOOLEAN WINDOW_SAFETY_ENABLED false

**Comment by Loreinator** [comment]
I just tested, and yes - if you had a window off screen and then started the program with this safety enabled, then it automatically forces the move chooser back to the default location (centre of primary monitor).

In general, I don't think the safety will be much of an issue to most users. Still, I included the override just in case some setup somewhere is adversely affected.

**Comment by EvilProfesseur** [comment]
great work, thanks for that!
