### ISSUE TITLE
Max one hit damage should be 9999

### ISSUE THREAD

**Issue by archershot** [Loreinator/Shuffle-Move#317]
many skill like unity power or last-ditch effort may cause hit point more than 9999 while shuffle move may cause some mistake for damage more than 9999 while the max hit is 9999

**Comment by Manitary** [comment]
I don't really understand, but there is no problem. Just tried with Attack Power Up, at 3 moves left LDE Dusknoir against a Spooked Ghost-type and a 5-match deals 19,800 damage, which is correct according to calculations: 110 x 2 x 2 x 2 x 1.5 x 15.

**Comment by archershot** [comment]
Sorry to my poor English. I means that the maximum real damage should restrict to 9999.  Even 19800 should adjust to 9999.  If current damage is x, it should change to min{9999,x} due to upper bound limit.

**Comment by Manitary** [comment]
That's not true. The numbers that appear over the board (lower part of the screen) are capped to 4 digits (9999), but on the upper screen you can see the real damage. You can also double check that the damage is fully dealt by looking at the score increment.

**Comment by archershot** [comment]
Thank you very much! I'm sorry to bother you. Best wishes!

**Comment by Manitary** [comment]
No problem! :)
