### ISSUE TITLE
Roster freezes the board ?

### ISSUE THREAD

**Issue by kpwbo** [Loreinator/Shuffle-Move#32]
In v0.3.20, opening the Roster, then closing it, freezes the board and the paint module.

To reproduce, simply open the Roster, then close it, then try to place icons on the board.

It *seems* like the actual data gets updated and a simulation happens according to the status bar at the bottom, but the board does not visually update. Also, trying to update the Score after that (using the arrows) does not work. Trying to change the number of Moves works, but once a number is picked that is different from the original number, the list stays open (but the simulation happens), so another click is necessary to close the list. Checking the Wood/Metal/Coin/Frozen/Mega checkboxes does not visually update the paint module.

I'm not sure if this problem is for me only, so I'll include a bug report zip if it helps : http://ge.tt/1L8FiiM2/v/0?c

**Comment by Loreinator** [comment]
Resolved on Development branch.

**Comment by Loreinator** [comment]
Rushing release out now for v0.3.21 to resolve this severe bug.

**Comment by Loreinator** [comment]
V0.3.21 is now out, please check if it adequately resolves this issue.

**Comment by kpwbo** [comment]
It seems that the issue is well resolved. :)
