### ISSUE TITLE
General issue with Escalation Battles on Shufflemove

### ISSUE THREAD

**Issue by Idaipuraisu** [Loreinator/Shuffle-Move#320]
The Total HP + HP/level for Pokémon in repeat Escalation battles has been incorrect since the moneymakers over GS have been randomly raising the Total HP levels. For future updates of Shufflemove Could we either fill  the Total HP + HP/level for each of all special types or have older Escalation Battles level update with Total HP + HP/level as a fill in just like current HP.

I really appreciate your updates & fixes. Thank you for your hard work within Pokémon shuffle community. I also really am thank for you adding the delete species from my suggestion. I use it everyday.

**Comment by Manitary** [comment]
Could you point out what are the mistakes? I personally update the HP values for every update as soon as we get some datamining done (ritchie/toshin pastebin, chinese wiki)

**Comment by Idaipuraisu** [comment]
Oh nevermind, I guess I just didn't give you enough time to update after
the datamine The newest version you corrected everything. thanks again
