### ISSUE TITLE
Account for potential double ability activations arising from unfreeze-drop delay

### ISSUE THREAD

**Issue by JustAnotherRandomLad** [Loreinator/Shuffle-Move#33]
Described in this bug report: http://ge.tt/6cLsjiM2/v/0

I mentioned it on Reddit a while ago - it's the "game treats turn as over if the only icons to fall are still unfreezing" thing, which can actually cause abilities to activate twice in one turn.

**Comment by Loreinator** [comment]
I'm not quite sure how to reliably detect that, we should compile all available information on the phenomenon for future inclusion - if we implement it wrong it could be worse than not implementing it at all.

**Comment by JustAnotherRandomLad** [comment]
If you wanted to handle it exactly the way the game does, you could have Shuffle Move "end" the move when the only icons still airborne are the unfreezing ones, and then just let the board "settle" and allow whatever lines up first to trigger an ability as if it was the result of a move.

**Comment by Loreinator** [comment]
I guess...

Maybe have it check that the only thing on the queues is an 'erase' task without anything to erase (that's how the program tracks unfreezing), then store the current chain count and reset the accessible chain count to force it to consider the next combos as 'first combos'.

**Comment by JustAnotherRandomLad** [comment]
That's how the game does it.

Results of my first test attempt at moving on the fly were ambiguous, but lean toward being negative. I'm going to try again in a few minutes.

**Comment by Loreinator** [comment]
Do we know the exact situation when this will occur? I.e. where exactly should I put the SimulationState.setChainPause() call? This is when it sets a counter to note when the last time the chain started over was - which is used to get the actual combo number for a given simulation (when equal to zero it allows effect activation).

**Comment by JustAnotherRandomLad** [comment]
If there is any moment at which nothing is falling and the only things being erased are barriers, that moment (which will be the very last frame of an unfreeze) is when the combo resets.

**Comment by Loreinator** [comment]
Pretty sure this is fixed in the next release. If it isn't please reopen this issue and we'll investigate a better place to put the check.

**Comment by Loreinator** [comment]
Was just playing the game before bed, and i noticed something - the metal blocks might START to disappear at the beginning of the level... but they don't actually allow immediate falling. They begin an erasure effect which keeps their tiles active for an unknown amount of time (at least 82 frames). An adjustment is necessary to the algorithm to account for this appropriately.

**Comment by Loreinator** [comment]
Nevermind, wrong issue.
