### ISSUE TITLE
F key bug

### ISSUE THREAD

**Issue by kpwbo** [Loreinator/Shuffle-Move#35]
If Express Mode is selected, and the F key is pressed, Frozen is toggled. However, if the mouse hovers over the board (or over "Paint", or over "Express" after having hovered above something else), pressing the F key no longer toggles Frozen, even if the mouse goes back somewhere else (such as above the Paint module).

After that glitch is triggered, selecting Paint Mode AND hovering the mouse over the board (or over "Express", or over "Paint" after having hovered above something else) will make the F key work as normal again.

To reproduce :
1) Open ShuffleMove (in Paint mode).
2) Select Express Mode, then don't move the mouse.
3) Press the F key to verify that it works (it should).
4) Hover the mouse over the board, or over "Paint" (without clicking).
5) Press the F key to verify that it works (it doesn't work !).

**Comment by Loreinator** [comment]
I think I see what's going on here. For some reason the code handling the switch between entry modes isn't fully engaged until after the mouse moves over the board.

**Comment by Loreinator** [comment]
Since this has such an easy workaround (move mouse over board) I'll leave this until the next normal release. There should be plenty of time to find the solution before then.

**Comment by kpwbo** [comment]
Yes, that's it. I worded the problem badly because my board was empty when testing the bug. But now that my board is full, I can see that what you described is what actually happens. So it's just a minor bug. :)
A huge thanks by the way for working on this program. :+1:

**Comment by Loreinator** [comment]
All fixed in the development branch
