### ISSUE TITLE
Update Chinese Translations

### ISSUE THREAD

**Issue by BeginnerSlob** [Loreinator/Shuffle-Move#364]
Chinese Translations are too old to read.
Some Pokemon's name is wrong according to the new Pokemon Games.
I want help fix it, but I can't find the Translation Files.

**Comment by Loreinator** [comment]
The i18n is hosted here in the github source:
https://github.com/Loreinator/Shuffle-Move/tree/master/i18n/shuffle/fwk

Any file that has _zh in the name is the Chinese localization files.

**Comment by BeginnerSlob** [comment]
OK, thanks
