### ISSUE TITLE
Allow last-3-turns abilities to proc when 4 turns remain

### ISSUE THREAD

**Issue by JustAnotherRandomLad** [Loreinator/Shuffle-Move#37]
In the game, the move counter is decreased *before* these abilities are accounted for, so you can actually set them off on your last 4 moves. Whether you want to account for this by doing what's in the title directly or by decrementing the move count before considering these abilities is up to you.

**Comment by Loreinator** [comment]
This can definitely be put in, it will just take a couple lines or so to make the adjustment.

**Comment by Loreinator** [comment]
Fixed in development branch, by reducing the move counter in the simulation core by 1.
