### ISSUE TITLE
Sky Blast is x2 Flying, not x1.2

### ISSUE THREAD

**Issue by avengah** [Loreinator/Shuffle-Move#38]
It looks like Sky Blast only adds 20% in the simulation. It's actually double damage for Flying types. (If you look at the pastebin, you see it's shown as 2x there.) This is important for the current competition, as Sky Blast will be used for the highest scores. Thanks!

I haven't tested this with the others to see if the program gets it right but just to clarify, Sinister and Pixie are x1.5, Pummel, Dragons and Pyre are x1.2, Double Normal is x2.5, Sky Blast is x2. Risk Taker multiplies by a random number between 1/3 and 3 (as shown in the misc. pastebin).

Pastebins: http://pastebin.com/u/xJakub

(I just pasted the Reddit posts here, as I have nothing more to add.)

**Comment by Loreinator** [comment]
I'll be sure to attend to this tonight when I get some time.

**Comment by Loreinator** [comment]
[Fixed here, so this issue is now resolved.](https://github.com/Loreinator/Shuffle-Move/commit/c3cfa65cc2135bc5ac773a6d30b97003a3cfacdd)
