### ISSUE TITLE
Make wooden blocks disappear when adjacent metal ones "expire"

### ISSUE THREAD

**Issue by JustAnotherRandomLad** [Loreinator/Shuffle-Move#39]
See title. Just saw that happen a few times.

**Comment by Loreinator** [comment]
Can you provide a screenshot? Does this happen before or after abilities are taken into account? Such as wood or metal removal abilities?

**Comment by JustAnotherRandomLad** [comment]
> screenshot?

Will do later.

> disruption-removing abilities?

Don't know. Will check soon - M-Venusaur provides a great opportunity for that.

**Comment by Loreinator** [comment]
By disruption removing abilities, I mean things like block smash and aerodactyl's mega - things that immediately target them. This is important because if the metal block auto-clear is delayed then these effects will be less effective overall. 

They also might cause the wood shatter to not occur - since a block removed by an ability does not count for shattering.

**Comment by JustAnotherRandomLad** [comment]
Yeah, I got that. Testing the timing for metal blocks is just a matter of activating Block Smash on a stage that starts out with them, but doesn't spawn any new ones - IIRC, Braixen will do. (Actually, that one would help answer the age-old question of "how does Stabilize+ interact with frozen disruption blocks," too. Honedge is probably a better idea for testing M-Aero.)

I have no idea how one could test the timing of the wooden blocks, though - it's fairly easy for normal abilities (just bring Stabilize+ to M-Venusaur once or twice and count the total number of disappearing blocks), but testing their interaction with M-Aero would be a nightmare. Can we assume that its activation timing is the same as for normal abilities?

**Comment by avengah** [comment]
I can confirm that this happened on the Electrike level. The map can be viewed here: http://www.pkparaiso.com/shuffle/lista-de-fases/fases-especiales.php?lang=eng

**Comment by JustAnotherRandomLad** [comment]
Oh, right, yes, it happened all the time on that one.

**Comment by Loreinator** [comment]
This should be in now on the development branch. Please take a look at the latest prototype [here](https://drive.google.com/open?id=0Bwi_f200YyRqfm5fOWMtbkVrd0RhQUJyTDR6V29WZFFBd0o4cl95VjlqUTkyNDRicS1GOVE) (i.e. the one with the highest last digit). If the wood shatter from metal blocks is not sufficiently simulated please post here with an example of what should be happening that isn't and I'll re-examine what needs to be done.
