### ISSUE TITLE
Save prompt on quitting?

### ISSUE THREAD

**Issue by avengah** [Loreinator/Shuffle-Move#40]
I saw just now on GameFAQs that someone was complaining that the program never saved his levels and he always had to reenter them for the team he was using. I usually remember but I also forgot last time.

So is there any chance of a dialogue box on quit that gives options including "Save & Quit"? It would be more convenient and reduce the aforementioned confusion. Thanks!

**Comment by Loreinator** [comment]
I guess he never looked at the file menu... Do you have a link to the post so I can go let him know about the current save system?

**Comment by Loreinator** [comment]
I can probably throw this in easily, I just never thought that would be a problem since Ctrl-S is so easy and commonplace as the save command.

**Comment by avengah** [comment]
Here. Most of it's on the second page if set to 50 posts per page: http://www.gamefaqs.com/boards/114531-/72365550

**Comment by Loreinator** [comment]
It seems you already said most of what I would have said! Thanks for keeping them informed for me. 

They do have a point though, I'll put in the save prompt for main window exiting in the next feature release.

**Comment by Loreinator** [comment]
i18n volunteers have been notified, hopefully the keys are ready by the time I send out this release (which I'll probably do on Wednesday).
