### ISSUE TITLE
Issue with block expiring

### ISSUE THREAD

**Issue by growlgrrl** [Loreinator/Shuffle-Move#41]
Something I've come across at least twice now is that when a block is expiring I don't see the predicted combo. It seems that the timing of when the block expires vs when the initial matches occur and skyfall starts is off somehow and icons aren't matching midair.

Sorry I'm can't be more specific, I'll watch out for it and try to see whats happening.

**Comment by Loreinator** [comment]
I think I might know the problem - it doesn't force a gravity update when the metal blocks expire... that might be the difference. I'll try it out tomorrow evening and see what I can find out.

**Comment by Loreinator** [comment]
I'll be doing the next release this evening when I get home, so hopefully this is fixed in the build.

**Comment by Loreinator** [comment]
It appears this is due to at least 82 frames of delay before the expiring metal blocks are actually gone.

I'll work on it more probably on Friday or Saturday.

**Comment by avengah** [comment]
I'm having what I think is the same problem. Here's my bug report: http://ge.tt/1Z9aetM2/v/0?c
Thanks again.

**Comment by Loreinator** [comment]
Fixed in development, if this occurs in v0.3.26 release please re-open.
