### ISSUE TITLE
Mode changes when using Move Chooser

### ISSUE THREAD

**Issue by avengah** [Loreinator/Shuffle-Move#43]
I keep it set to Express Mode so I can enter the board quickly every turn. As soon as I click Do Move in the Move Chooser, it changes to Paint Mode. It does this every time and it's annoying! Please could you stop this from happening? Thanks.

EDIT: Just to save me opening another one, would it be possible for an option to reset the level to the start? For example, if I'm playing the Venusaurite competition and want to try again, I have to select a different level and then the competition level again to reset the turns and score to 15 and 0, respectively. Thanks!

**Comment by Loreinator** [comment]
I'll put this in as a toggle-able feature on the move preferences window. It seems everything is getting shoved into that options list, heh.

**Comment by Loreinator** [comment]
Key requests sent to the three translators, It is in for the next release as a simple toggle option in the move preferences window (ON by default, but if you toggle it off and save with Ctrl-S you will retain your preference).
