### ISSUE TITLE
Consider NVE pokemon as disruptions

### ISSUE THREAD

**Issue by mawilek** [Loreinator/Shuffle-Move#44]
Since Shuffle Move can prioritize removing disruptions, it would be nice to consider any NVE pokemon as disruptions.
When playing against Darkrai, removing 6 NVE Cresselia/Darkrai with a Lucario match has higher priority, than removing a single metal block.
It would also be nice to consider empty spaces as disruptions, so that Barriers at the top of the board with empty spaces below would have higher priority.

**Comment by avengah** [comment]
I agree but with the proviso that such behaviour can be toggled. Sometimes you want an NVE on your team for its ability, and disruption Pokes aren't always NVE. I guess a tick box by each Pokemon to tell the program whether you want it removed or not.

**Comment by Loreinator** [comment]
This should be tied in as part issue https://github.com/Loreinator/Shuffle-Move/issues/16

NVE species are not disruptions, only blocks which boost counterattack are disruptions. However, I agree that you might want to prioritize removal of many NVE tiles while maintaining a high score. This could definitely be part of the configurable grading modes feature (which I haven't yet had time to do, but once it seems straight forward to implement I will immediately get on that). 

Closing issue as a duplicate, but I'll transfer your comments over there so this idea doesn't get lost in the winds.
