### ISSUE TITLE
Improper red/blue highlight order.

### ISSUE THREAD

**Issue by WolfHeroEX** [Loreinator/Shuffle-Move#45]
https://drive.google.com/file/d/0BxbI5_3DLDYCTnVmNW0taW1lSEE

In this particular instance, moving Giratina to Yveltal would produce a Power of Four+ effect, however, the program suggested me to move Yveltal to Giratina.

**Comment by Loreinator** [comment]
Which version are you using? The logs in that zip show it as v0.3.9 - the current version is v0.3.22. Please update and see if the same issue occurs.

**Comment by WolfHeroEX** [comment]
For some strange reason the new bug zip didn't get made, I thought this one was it.

It's indeed an old bug zip. If I have this happen again I'll try to make a new one, it's weird that it didn't actually create it.

**Comment by Loreinator** [comment]
For v0.3.23 I've fixed the bug zip naming convention to be more clear about when they were created (including time zone). https://github.com/Loreinator/Shuffle-Move/commit/8406e9d6a2a8bc0af38312fb006323fcd40c54fd

**Comment by Loreinator** [comment]
If you find another instance where this occurs, and you're able to make a bug report zip please re-open this issue and link to the zip so I can investigate.
