### ISSUE TITLE
Disruption Delay option

### ISSUE THREAD

**Issue by avengah** [Loreinator/Shuffle-Move#47]
I've been using the new option for disabling certain abilities - namely, Burn when using a Fire team for the competition. It's useful if you're using a Disruption Delay. For example, Burn is one of several abilities that won't activate if DD is active. You can stop them from activating by unticking the boxes, then ticking them again once the DD wears off.

I have two improvements I'd like to suggest regarding this. Firstly, would it be possible to have it set so that only abilities possessed by Pokemon in the current team (including disruption Pokemon, of course) appear in the list? Because there's no point disabling abilities that aren't going to activate anyway.

Secondly, how about a Disruption Delay tick box on the main screen (near the Attack+ option)? Ticking that would disable all the abilities that won't activate while DD is active. This includes Astonish, Burn, Chill, Flap, Freeze, Paralyse, Quake, Sleep Charm, Spookify.

In fact, it might be possible to take this one step further and have the DD disable automatically at half the turns left (rounded down), so a level with 15 turns would wear off when the counter reaches 7. However, remember that if the very first match in a turn evolves a Mega, it's delayed by one turn so it would wear off at 6.

Also, +5 turns would have to be implemented too, as this affects the DD. In an Escalation Battle with 18 turns, it would wear off at 9 normally. However, with the +5 it would wear off at 11, so after 12 turns have passed.

Just some ideas I thought you might find help improve the program! Thanks again.

**Comment by Loreinator** [comment]
Is this the complete list of all abilities that can't occur during DD?

Astonish, Burn, Chill, Flap, Freeze, Paralyse, Quake, Sleep Charm, Spookify

If so, I guess this wouldn't be too hard of a change to implement. I'll have to include a +5 moves button along side the DD option though. 

Perhaps I should move all these 'Item' based stage modifiers to a new panel, given that its starting to fill up the paint pallet a fair bit. Any ideas on a better layout for the main window, or should this be its own window?

**Comment by avengah** [comment]
Yes, that's all of them. Anything that affects the enemy directly, with the exception of Mind Zap and Prank (technically they just affect the disruption counter), since only one status can be active at a time. Once the DD wears off, a status can occur on the next turn.

I'm not sure about a layout, but I normally maximise the window and have the move chooser on the right, under the team. Buttons controlling the level could go just underneath the board I guess? Things like toggling blocks and coins are unlikely to be changed mid-level (you'll know what's going to appear, at least after playing the level once) so they can stay over on the right.
