### ISSUE TITLE
Rocks aren't destroyed if they're falling when a match goes off next to them

### ISSUE THREAD

**Issue by avengah** [Loreinator/Shuffle-Move#48]
In my game, column 3 was full of rocks. I entered the board into Shuffle Move and it predicted the board correctly except it only showed one rock left at the bottom of column 3. However, because the rocks were falling during part of the combo, there were actually three rocks left at the bottom of column 3. Here's my file: http://ge.tt/2BgUN2N2/v/0?c

**Comment by Loreinator** [comment]
Can you reupload the bug report zip to google drive or some other file sharing service? ge.tt doesn't work anymore with windows 10. 

Anyway, I gather that this just means that Wood blocks themselves are immune to shattering while they are falling? That's a simple check and might just be a 1-liner to fix.

**Comment by avengah** [comment]
Here: https://drive.google.com/file/d/0B8j46iq8jAHVZlBEYVhESTNHM1k/view?usp=sharing

And here's the one I uploaded the other day: https://drive.google.com/file/d/0B8j46iq8jAHVenJmSTN0dDBSSEU/view?usp=sharing

**Comment by Loreinator** [comment]
Closing this issue, since it should be fixed in the development branch now. If it isn't please give an example where it fails to properly remove the correct number of wood blocks and I'll see where the simulation is falling short (and fix it).
