### ISSUE TITLE
Assemble all default boards

### ISSUE THREAD

**Issue by Loreinator** [Loreinator/Shuffle-Move#51]
This requires no programming knowledge, and simply needs someone to go through and save the initial pre-determined state of each board that actually is predetermined in some way. Once that is done, simply upload the report zip and I can include the boards into the next release's default boards. [The page here](http://www.pkparaiso.com/shuffle/lista-de-fases.php?lang=eng) lists all the stages, some of which have pre-determined board layouts (at least in part).

**Comment by JustAnotherRandomLad** [comment]
On it right now.

Two potential problems:
1) Some of the boards (like Bulbasaur) have predetermined *arrangements* of mons in your team.
2) Some of the predetermined parts extend above the top of the screen (like with Buneary and M-Garchomp).
3) Some of the boards (like Swirlix) have random arrangements, but certain spaces start out with barriers over them.

These three types of predetermination can't be accounted for in the program as it exists now; is that alright?

**Comment by JustAnotherRandomLad** [comment]
Here you go!

https://drive.google.com/open?id=0B9AJEgC2diKdQ2ZldzZXN3ltSEE

**Comment by Loreinator** [comment]
1) Some of the boards (like Bulbasaur) have predetermined arrangements of mons in your team.

- This may possibly be accounted for in the future, but it is a very far-off feature. It will likely come in after the Meowth solver is implemented (since there is a pattern to the disruptions).

2) Some of the predetermined parts extend above the top of the screen (like with Buneary and M-Garchomp).

- I'm still not quite sure how to handle that part... the user has no way to confirm how far along it has progressed, nor validate that the feed is correct. The only way for this to happen would be for the user to have some tool that shows the feeder state and allows integration into the boards for simulations while also diminishing the feeder perfectly. This will also require that the result of a move is chosen by the user - i.e. which effects happened or didn't happen, and what the actual board state is now. Very complicated stuff so I don't think it will be accounted for any time soon in a real usable sense. There MIGHT be some simpler way to use it to find the best opening move sequence for a given stage and board configuration, which would be more useful as an entirely separate program that just spits out a bunch of moves so that guides can be more accurate.

3) Some of the boards (like Swirlix) have random arrangements, but certain spaces start out with barriers over them.

- You mean they're frozen? yea, i saw that on Lugia's map. I'm not sure how to handle that, since the paints set the frozen state, and the air block in the program should never be 'frozen' really. It might be ok to change this though, but I'm not sure it makes sense to allow boards to store 'frozen' air - it would also require that paints don't set frozen anymore for this to actually be useful in some way.

These types of predetermination can't be accounted for in the program as it exists now; is that alright?

- That should be fine, the goal with the default boards is to reduce the input time for the majority of users. If they load up a new stage and the board is already 60% filled in they will be happier than if it was blank.

**Comment by JustAnotherRandomLad** [comment]
Alright, then the report I posted earlier contains all the default boards you're looking for (except for Emboar and Carnivine, which aren't in SM yet).

**Comment by Loreinator** [comment]
You need to make the google drive link shared, its private right now.

**Comment by JustAnotherRandomLad** [comment]
Oops - try again now.

**Comment by Loreinator** [comment]
All done, thank you very much for going through all those stages!

**Comment by JustAnotherRandomLad** [comment]
Eh, it only took an hour, and I was super bored. :P
