### ISSUE TITLE
Fix removal of Mega Evolving icons when unfrozen

### ISSUE THREAD

**Issue by JustAnotherRandomLad** [Loreinator/Shuffle-Move#52]
I know the title's a bit unclear, so I'll explain in a bit more detail:

In the game, if you make a match of something that then Mega Evolves as a result of the match (Sableye, in my case just now), but that match contains frozen icons, those icons are *not* removed - they stay there, like any other non-Mega icon. In Shuffle Move, however, the icons are removed as if they were Mega when they were matched.

Bug report: https://drive.google.com/open?id=0B9AJEgC2diKdU0wwZGdrNElfaUE

**Comment by Loreinator** [comment]
I think I know what's going wrong here. A simple fix - the check for "Is this a mega matchup" needs to be stored AT the activation time, not at the completion of the erase. I'll see what I can do tonight when I have time. I may or may not be doing a release tonight to include this bug fix.

**Comment by Loreinator** [comment]
Actually, it turns out that it was far simpler than that. The 'is it a mega matchup' is inherent to the design of the simulation. The problem was that the erasure effect was overriding that information.
