### ISSUE TITLE
Remove "double matching" when entire line of icons is frozen

### ISSUE THREAD

**Issue by JustAnotherRandomLad** [Loreinator/Shuffle-Move#53]
Just discovered this accidentally: when disruptions or the starting board layout result in a full matching line of frozen mons, the barriers are first removed (at the same rate as they would be normally) without being scored, and *then* the match is done. Shuffle Move seems to score the line twice, rather than just once.

(Which means I won't be able to test the double-cross-matching thing with Banette even if I get my hands on a good camera... :/)

**Comment by Loreinator** [comment]
So a match won't even activate properly if it is fully frozen? It has to thaw first? wow, I never knew that - does this behavior allow activation of their effect, count as a combo, score, mega progress, etc? I think we need to clearly identify all the aspects of this behavior before implementing the solution for it.

**Comment by JustAnotherRandomLad** [comment]
No, no, no, and no - at least a few of those were tested on the Banette stage, and the rest I noticed against Mega Gengar right before posting this.


Sent from my Samsung device

-------- Original message --------

**Comment by JustAnotherRandomLad** [comment]
(To clarify: the barriers are all removed as if wiped by Barrier Bash if such a line is ever detected - *before* any matching or scoring occurs.)


Sent from my Samsung device

-------- Original message --------

**Comment by Loreinator** [comment]
When the barriers are cleared (i.e. the match thaws), and there's air below at least one of the blocks, does it combo or does it fall? I've worked out most of the other parts of the implementation for this tweak, but I can't proceed until I know the exact line to add it on or it won't behave properly.

**Comment by JustAnotherRandomLad** [comment]
It falls.

Also, FWIW, the unfreezing follows normal match priority. For example, if a 3x3 cross-match is formed with the vertical line fully frozen, the horizontal line is cleared first, unfreezing the intersection point. If this causes that point to fall (as with an L-match with the corner suspended over air), the vertical match doesn't happen.

**Comment by JustAnotherRandomLad** [comment]
Oh, and something else: if a match that unfreezes one or more blocks activates Quirky(+), the ability can target the freshly unfrozen icons.

**Comment by Loreinator** [comment]
I've made a change which I hope addresses most if not all of this issue. Please check and let me know if it works. The build should end in 68 or higher in this folder: https://drive.google.com/open?id=0Bwi_f200YyRqfm5fOWMtbkVrd0RhQUJyTDR6V29WZFFBd0o4cl95VjlqUTkyNDRicS1GOVE
