### ISSUE TITLE
Finding location of zip directly from the Updater

### ISSUE THREAD

**Issue by kpwbo** [Loreinator/Shuffle-Move#56]
Hello. :)
Would it be possible to implement a button in the ShuffleMove Updater window that opens the location of the downloaded zip file ? In this way, users can click on "Get Newest Version" (or "Force") to download the zip, then click on "Open Zip Location" (or whatever name you choose for the button) to open the location of the zip in the default file manager (like Windows Explorer on Windows systems).

**Comment by Loreinator** [comment]
Currently built in the development branch, seems to work fine on Windows and I'll test it out on the others later today.

**Comment by Loreinator** [comment]
We'll need a quick test that the bug report feature will open to the bugs folder for each platform/OS type.

[See here for the prototype](https://drive.google.com/open?id=0Bwi_f200YyRqRllJN0hHa21fTm8)

I use the exact same code to handle opening of downloaded zips and the opening of bug report zips, so it should be fully testable through the report bug GUI alone.

**Comment by Loreinator** [comment]
So far, I've tested it on Windows 10 and it works perfectly fine.

Test Case:

1) Open the prototype program
2) Create a bug report through the GUI
3) Observe that your default file manager opens the folder which contains this new bug report.

If step 3 works and opens the correct folder without issue, then the test is successful.

**Comment by Loreinator** [comment]
Assuming this works correctly, I'll be pushing out a new version sometime during this long weekend - maybe Monday, but I haven't decided yet.

**Comment by kpwbo** [comment]
I can confirm that it is working on my Windows 8.1 system. :)

**Comment by Loreinator** [comment]
Just tested it in my Ubuntu 14.04 virtual machine, and it works perfectly.

**Comment by Loreinator** [comment]
It even works in MobaXTerm's automatic X11 forwarding, laggy but it still works (it barely has a desktop, and it can still show you the bug folder).

**Comment by Loreinator** [comment]
We just need someone on Macintosh to test it out and we're set.

**Comment by Loreinator** [comment]
Since it works well enough on Ubuntu and both Windows 10 and 8.1, I can't see any real reason why it wouldn't work on Macintosh - the code itself is very simple and uses the built-in desktop API for cross-platform usage. If anyone on Mac has issues we'll resolve them if possible. Closing this issue since there is no more to be done.
