### ISSUE TITLE
Settle problem

### ISSUE THREAD

**Issue by avengah** [Loreinator/Shuffle-Move#60]
The game wants me to settle this board, but there's nothing to settle. Pressing "settle" doesn't do anything. I loaded an older version and it worked fine.

It also didn't ask me whether I wanted to save (after doing this bug report). It just saved anyway, and reloaded the board when I loaded the older version.

https://drive.google.com/file/d/0B8j46iq8jAHVM3dIbkNqcG9faFk/view?usp=sharing

**Comment by Loreinator** [comment]
Looking into this now

**Comment by Loreinator** [comment]
Reproduced in development environment, digging into the cause, I should be able to find a solution pretty quickly.

**Comment by Loreinator** [comment]
I found the cause and corrected the problem. If this doesn't fix the problem please re-open this issue.I found the cause and corrected the problem. If this doesn't fix the problem please re-open this issue.
