### ISSUE TITLE
Risk Taker multiplier should be any between 1/3 and 3 instead of exactly 1/3 or 3

### ISSUE THREAD

**Issue by ShuffleBugs** [Loreinator/Shuffle-Move#66]
Currently it's coded as a random boolean choice of ⅓x or 3x.

**Comment by ShuffleBugs** [comment]
I ran the numbers myself with a team of risk takers of same power. Note that there's truncation of damage, e.g., 70 * 1/3 = 23.333 results in 23 damage, so the calculated multiplier is 0.32 below.

2.22
0.61
0.66
2.65
2.18
1.45
1.11
2.07
1.89
2.88
1.50
2.91
1.69
2.07
0.54
1.47
0.68
1.14
2.91
2.14
1.46
1.12
1.09
2.30
1.43
1.05
1.57
2.58
2.27
0.89
2.49
1.66
1.96
2.12
0.66
0.43
1.14
1.82
1.18
2.51
1.46
0.85
0.82
2.70
2.50
0.58
0.70
2.72
2.69
1.03
2.53
2.03
0.57
1.11
0.62
0.74
0.96
1.77
0.57
1.18
2.49
2.55
1.76
2.86
1.74
2.54
2.72
2.93
1.26
1.23
1.50
1.26
2.81
0.32
1.86
0.57
1.32
0.99
1.49
2.30
0.79
0.90
2.26
2.21
2.21
2.99
0.91
2.87
0.54
0.69
2.04
0.71
0.76
0.34
2.46
1.94
1.09
2.03
1.63
2.63
1.91
0.67

**Comment by Loreinator** [comment]
It seems that over the distribution it is mostly uniform, good find!
