### ISSUE TITLE
Don't center text in move choose to allow for easier scanning

### ISSUE THREAD

**Issue by ShuffleBugs** [Loreinator/Shuffle-Move#68]
Left a comment https://github.com/Loreinator/Shuffle-Move/commit/215285e97e6407324ca6af94ded1b7f5a7f08525#diff-ac7b3cf2ec9f2ab18b4680529769d40aR167

Because the text is centered, it's very hard to scan when there's varying numbers past the decimal point. This usually happens when running with multiple simulations with random effects.

I noticed this when sorting by combos looking for something with a minimum of 3 moves, but sorting by combos will have results like [1-10] or [2-8] or [3-5] all with different weighted averages.

**Comment by Loreinator** [comment]
Seems reasonable I guess, pushing the change now into the file - it should be ready for testing in a few minutes via the development folder.

Btw if you want to test out the latest development build, check [here](https://drive.google.com/open?id=0Bwi_f200YyRqfm5fOWMtbkVrd0RhQUJyTDR6V29WZFFBd0o4cl95VjlqUTkyNDRicS1GOVE) and download the highest final digit file (its the build number in Jenkins).

**Comment by Loreinator** [comment]
Check it out in the development branch when you have time, re-open this issue if it is not working quite right.

**Comment by ShuffleBugs** [comment]
Thanks! This looks great:
![screen shot 2015-09-08 at 11 35 43 am](https://cloud.githubusercontent.com/assets/14175519/9744002/2dc9d23a-561e-11e5-8214-63c1c5caf0a0.png)

Much easier to scan than before:
![screen shot 2015-09-08 at 11 37 16 am](https://cloud.githubusercontent.com/assets/14175519/9744010/34be6588-561e-11e5-9671-0f4b88202ebf.png)
