### ISSUE TITLE
"Switch to Paint Mode Automatically" causes visual errors 

### ISSUE THREAD

**Issue by Stixter94** [Loreinator/Shuffle-Move#74]
Having it enabled causes the GUI to display that you're currently in "Paint" mode, even though it controls like Express mode.

To reproduce: Press CTRL+Enter while in Express mode (clicking on "Do Move" doesn't make it occur) and press any team hotkey.
If you click on the board it works just as intended.

[Bug report .zip](https://www.dropbox.com/s/gjrpg66qhvl8iom/bugReport_20150913.zip?dl=0)

**Comment by Loreinator** [comment]
Confirmed, neat find! Looking into the cause now.

**Comment by Loreinator** [comment]
When the build completes, can you confirm that the bug is fixed? The link should be mentioned in the console output [here](http://loresoftworks.noip.me:8042/job/Upload%20Development%20to%20Google%20Drive/43/console) similar to the line:

Google drive link is:

**Comment by Stixter94** [comment]
The bug is indeed fixed.
