### ISSUE TITLE
Allow team members to be flagged as 'disruptions'

### ISSUE THREAD

**Issue by Loreinator** [Loreinator/Shuffle-Move#77]
From [here](https://www.reddit.com/r/ShuffleMove/comments/3lf0xt/found_a_pair_of_bugs_with_barriers_and_rocks/).

Also, do you think you could make possible to select a species in the team builder as a disruption? I mean, that would be cleared by Eject, and would count toward a disruption when you rank the score by disruption. In stages with lots of enemy pokemon is not very useful, but when there is just one or a few, it really helps.

**Comment by avengah** [comment]
Does Eject currently work in the simulation? If not, I think a good temporary fix would be to have it remove any Pokemon not in the first four slots of the team selection. But not coins, rocks or blocks, obviously.

**Comment by avengah** [comment]
Actually, now that I think about it, that won't work on levels with "Additional" Pokes, because Eject won't remove them - only Pokes that are fixed on the initial board, fixed in the preset skyfall or brought in by disruptions are removed by Eject.

**Comment by Loreinator** [comment]
Fixed with commit 5c385d9
