### ISSUE TITLE
Java issue

### ISSUE THREAD

**Issue by vbnm193** [Loreinator/Shuffle-Move#95]
A Java exception has occurred. Please help.

**Comment by kpwbo** [comment]
Can you give more details about the issue ? How did the error happen ? What were you trying to do ? Can you provide a screenshot of the error message or create a bug report (in Shuffle Move : Help -> Bug Report... -> Create Bug Report, then upload it to a file sharing website and post the link here) ? This will help solve the problem. :)

**Comment by vbnm193** [comment]
I am not able to open up shuffle move

**Comment by vbnm193** [comment]
i am not able open shuffle move to do so. I am receiving an error saying a java exception has occurred. I think I have been able to pinpoint that it is because I do not have Java 8, but I am unable to download Java 8. Certain websites are blocked for me and I do not why. I have turned off my firewall and removed my antivirus, but websites such as gamefaq.com and downloading java give me a connection error. I would give a screen shot, but I do not know if there is a command to take a screen shot on a windows computer.

**Comment by Loreinator** [comment]
This is a problem with your network itself it seems. You may either be
behind a custom firewall or be using a DNS that blocks it. If you can, try
setting your DNS settings to Google's (8.8.8.8 and 4.4.4.4 I think).

-Andrew

**Comment by vbnm193** [comment]
Woah, I do not know why, but my internet connection is unknown and when I try to change the DNS it says access denied.

**Comment by Loreinator** [comment]
Try rebooting, and if that doesn't work then search for connectivity
troubleshooting steps for your version of Windows. If that still doesn't
work, complain to your network guy.

-Andrew

**Comment by vbnm193** [comment]
OMG thank you so much I was able to get it to work
