### ISSUE TITLE
Incorrect species info

### ISSUE THREAD

**Issue by coeusite** [Loreinator/Shuffle-Move#96]
Please make an update for Landorus and Thundurus.

In ```Shuffle-Move/resources/config/defaults/species.txt```

from 
```
SPECIES Tornadus 3370 70 FLYING POWER_OF_5_P
SPECIES Thundurus 3380 70 FLYING POWER_OF_5_P
SPECIES Landorus 3390 70 FLYING NONE
```

to
```
SPECIES Tornadus 3370 70 FLYING POWER_OF_5_P
SPECIES Thundurus 3380 70 ELECTRIC POWER_OF_5_P
SPECIES Landorus 3390 80 GROUND POWER_OF_5_P
```
Thank you.

P.S. adding this modification in ```config/species.txt``` does not work.

**Comment by coeusite** [comment]
As a temporary solution,
adding ```RESOURCE SPECIES config/species.txt``` to config/paths.txt,
and adding species.txt to the jar package: ```ShuffleMove.jar/config/species.txt```

**Comment by Loreinator** [comment]
This is already done locally in my dev environment, it will be going in with 0.3.40 which as I mentioned on Tuesday should be coming out before I go to bed tonight. [See here](https://www.reddit.com/r/ShuffleMove/comments/3vwypn/v0340_release_plan/cxu6pib&context=1)

For temporary solutions, you don't need to make such radical changes. Just modify the config/species.txt file which is already referenced in the default paths.txt file

>FILE SPECIES config/species.txt

**Comment by coeusite** [comment]
Thank you!

However, modifying ```config/species.txt``` does not work for my friend (Win) or me(Linux).

**Comment by Loreinator** [comment]
Really? Are you sure you were modifying the correct location? To find the location it uses, hit Ctrl-B and a popup with a zip will appear. Go up one level and there should be a config folder there. Go into it and that species.txt should be the one you want.

**Comment by coeusite** [comment]
The following test is based on a clean installation of the latest ShuffleMove.

Here is ```config/path.txt```
```
RESOURCE PREFERENCES config/defaults/preferences.txt
RESOURCE SPECIES config/defaults/species.txt
RESOURCE STAGES config/defaults/stages.txt
RESOURCE STAGES_MOBILE config/defaults/stages_mobile.txt
RESOURCE ICONS config/defaults/icons.txt
RESOURCE HELP_FILE docs/help.html
RESOURCE ABOUT_FILE docs/about.html
RESOURCE BUGS_FILE docs/bugs.html
RESOURCE UPDATE_FILE docs/update.html
RESOURCE EFFECTS config/defaults/effects.txt
RESOURCE EFFECTS_MOBILE config/defaults/effects_mobile.txt
RESOURCE GRADING_MODES config/defaults/gradingModes.txt
FILE PREFERENCES config/preferences.txt
FILE SPECIES config/species.txt
FILE STAGES config/stages.txt
FILE STAGES_MOBILE config/stages_mobile.txt
FILE ICONS config/icons.txt
FILE TEAM config/teamsData.txt
FILE ROSTER config/rosterData.txt
FILE BOARD config/boards/board.txt
FILE GRADING_MODES config/gradingModes.txt
STRING TYPE_PATH_FORMAT img/types/%s.png
STRING DEFAULT_BOARD_STAGE_CONFIG config/defaults/boards/%s.txt
```

Here is ```config/species.txt``` for test
```
SPECIES Regigigas 3540 100 NORMAL NONE
```

However, Regigigas still has 90 atk-power with Hyper-Punch skill in ShuffleMove.
![snapshot](https://i.v2ex.co/SFDOJ77y.png)


Here is logs in console:
```
[*@* Shuffle-Move]$ bash launch.sh
libpng warning: iCCP: known incorrect sRGB profile
[Dec 11, 2015 12:17:01 PM] [FINE] /home/*/Shuffle-Move/config/icons.txt (No such file or directory)
[Dec 11, 2015 12:17:02 PM] [FINE] /home/*/Shuffle-Move/config/gradingModes.txt (No such file or directory)
[Dec 11, 2015 12:17:02 PM] [FINE] /home/*/Shuffle-Move/config/stages.txt (No such file or directory)
[Dec 11, 2015 12:17:02 PM] [WARNING] No such file available: /home/*/Shuffle-Move/config/boards/board.txt
[Dec 11, 2015 12:17:02 PM] [FINE] /home/*/Shuffle-Move/config/teamsData.txt (No such file or directory)
[Dec 11, 2015 12:17:02 PM] [FINE] /home/*/Shuffle-Move/config/rosterData.txt (No such file or directory)
[Dec 11, 2015 12:17:02 PM] [INFO] Welcome to ShuffleMove v0.3.40!
[Dec 11, 2015 12:17:02 PM] [FINE] Result set: null
[Dec 11, 2015 12:17:02 PM] [FINE] New message is: No Move: 
[Dec 11, 2015 12:17:02 PM] [INFO] Simulation Started.
[Dec 11, 2015 12:17:02 PM] [FINE] Preparing board, moves & feeder
[Dec 11, 2015 12:17:02 PM] [FINE] Making tasks, prep took 1ms
[Dec 11, 2015 12:17:02 PM] [FINE] Getting results, init took 0ms
[Dec 11, 2015 12:17:02 PM] [FINE] Returning best results, the decision took 0ms
[Dec 11, 2015 12:17:04 PM] [INFO] Program is up to date. Newest version is v0.3.40 and your current version is v0.3.40.
```

**Comment by coeusite** [comment]
All right, I think I know what happened...

This ```config/species.txt``` does work:
```
LONG BUILD_DATE 1449796329325
STRING VERSION v0.3.40
SPECIES Regigigas 3540 120 NORMAL NONE
```

**Comment by Loreinator** [comment]
Ahhh I see what happened - The version you were providing was interpreted as 'obsolete' compared to the version it was using. I'll take a look at the code that handles obsolete configs just to make sure its a < and not a <=.

**Comment by coeusite** [comment]
Gotcha. Thank you!

**Comment by Loreinator** [comment]
Hey, if you want a version that will be the maximum version possible, you could go with something absurd like this:

```
LONG BUILD_DATE 9223372036854775807
STRING VERSION v2147483647.2147483647.2147483647
```

Basically, the way it works is that the date in millis since epoc is the first value, so max java long is the highest it could ever be.
String version, is matched via regular expression to this: 

```
v(\\d+)\\.(\\d+)\\.(\\d+)
```

So, we can just put the max integer there, which is 2147483647

This would be the ideal 'hack' time stamp and version number for this kind of purpose.

**Comment by coeusite** [comment]
_(:З」∠)_
